
package bmail;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

public class Bmail extends javax.swing.JFrame {

	public Bmail() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      mainPanel = new javax.swing.JPanel();
      loginCard = new javax.swing.JPanel();
      logoLogin = new javax.swing.JLabel();
      registerButton = new javax.swing.JButton();
      loginPanel = new javax.swing.JPanel();
      usernameLabel = new javax.swing.JLabel();
      passwordLabel = new javax.swing.JLabel();
      passwordBox = new javax.swing.JPasswordField();
      usernameBox = new javax.swing.JTextField();
      submitButton = new javax.swing.JButton();
      loginLabel = new javax.swing.JLabel();
      otherEmailButton = new javax.swing.JButton();
      otherLoginPanel = new javax.swing.JPanel();
      logoOther = new javax.swing.JLabel();
      homeOtherButton = new javax.swing.JButton();
      registerOtherPanel = new javax.swing.JPanel();
      registerOtherLabel = new javax.swing.JLabel();
      usernameOtherLabel = new javax.swing.JLabel();
      usernameOtherBox = new javax.swing.JTextField();
      passwordOtherLabel = new javax.swing.JLabel();
      passwordOtherBox = new javax.swing.JPasswordField();
      emailOtherLabel = new javax.swing.JLabel();
      emailOtherBox = new javax.swing.JTextField();
      emailPasswordOtherLabel = new javax.swing.JLabel();
      emailPasswordOtherBox = new javax.swing.JPasswordField();
      emailServerLabel = new javax.swing.JLabel();
      emailServerBox = new javax.swing.JTextField();
      submitOtherButton = new javax.swing.JButton();
      registerCard = new javax.swing.JPanel();
      logoRegister = new javax.swing.JLabel();
      homeButton = new javax.swing.JButton();
      registerPanel = new javax.swing.JPanel();
      registerLabel = new javax.swing.JLabel();
      usernameLabelR = new javax.swing.JLabel();
      usernameBoxR = new javax.swing.JTextField();
      passwordLabelR = new javax.swing.JLabel();
      passwordBoxR1 = new javax.swing.JPasswordField();
      passwordComfLabel = new javax.swing.JLabel();
      passwordBoxR2 = new javax.swing.JPasswordField();
      emailLabel = new javax.swing.JLabel();
      emailBox = new javax.swing.JTextField();
      submitButtonR = new javax.swing.JButton();
      inboxCard = new javax.swing.JPanel();
      logoInbox = new javax.swing.JLabel();
      logoutButton = new javax.swing.JButton();
      inboxLabel = new javax.swing.JLabel();
      inboxPanel = new javax.swing.JPanel();
      composeButton = new javax.swing.JButton();
      deleteButton = new javax.swing.JButton();
      openButton = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      inboxTable = new javax.swing.JTable();
      composeCard = new javax.swing.JPanel();
      composeLogo = new javax.swing.JLabel();
      inboxButton = new javax.swing.JButton();
      composePanel = new javax.swing.JPanel();
      composeLabel = new javax.swing.JLabel();
      toLabel = new javax.swing.JLabel();
      toBox = new javax.swing.JTextField();
      subjectLabel = new javax.swing.JLabel();
      subjectBox = new javax.swing.JTextField();
      messageLabel = new javax.swing.JLabel();
      sendButton = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      messageArea = new javax.swing.JTextArea();
      openCard = new javax.swing.JPanel();
      openLogo = new javax.swing.JLabel();
      inboxButtonO = new javax.swing.JButton();
      openPanel = new javax.swing.JPanel();
      fromLabel = new javax.swing.JLabel();
      fromBox = new javax.swing.JTextField();
      subjectLabelO = new javax.swing.JLabel();
      subjectBoxO = new javax.swing.JTextField();
      messageLabelO = new javax.swing.JLabel();
      deleteButtonO = new javax.swing.JButton();
      jScrollPane3 = new javax.swing.JScrollPane();
      messageAreaO = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().setLayout(new java.awt.CardLayout());

      mainPanel.setMinimumSize(new java.awt.Dimension(655, 534));
      mainPanel.setLayout(new java.awt.CardLayout());

      loginCard.setBackground(new java.awt.Color(204, 204, 255));

      logoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      registerButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      registerButton.setText("Register");
      registerButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            registerButtonActionPerformed(evt);
         }
      });

      loginPanel.setBackground(new java.awt.Color(204, 204, 255));

      usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      usernameLabel.setLabelFor(usernameBox);
      usernameLabel.setText("Username");

      passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      passwordLabel.setLabelFor(passwordBox);
      passwordLabel.setText("Password");

      submitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      submitButton.setText("Submit");
      submitButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitButtonActionPerformed(evt);
         }
      });

      loginLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      loginLabel.setText("Login");

      otherEmailButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      otherEmailButton.setText("Login With Other Email Service");
      otherEmailButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            otherEmailButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
      loginPanel.setLayout(loginPanelLayout);
      loginPanelLayout.setHorizontalGroup(
         loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(loginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(loginPanelLayout.createSequentialGroup()
                  .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(usernameLabel)
                     .addComponent(passwordLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(usernameBox)
                     .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                  .addComponent(submitButton)
                  .addGap(67, 67, 67)))
            .addGap(0, 49, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(otherEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28))
      );
      loginPanelLayout.setVerticalGroup(
         loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(loginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(usernameLabel)
               .addComponent(usernameBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(passwordLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(submitButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(otherEmailButton)
            .addContainerGap())
      );

      javax.swing.GroupLayout loginCardLayout = new javax.swing.GroupLayout(loginCard);
      loginCard.setLayout(loginCardLayout);
      loginCardLayout.setHorizontalGroup(
         loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(loginCardLayout.createSequentialGroup()
            .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginCardLayout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(logoLogin))
               .addGroup(loginCardLayout.createSequentialGroup()
                  .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(loginCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registerButton))
                     .addGroup(loginCardLayout.createSequentialGroup()
                        .addContainerGap(196, Short.MAX_VALUE)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 174, Short.MAX_VALUE)))
            .addContainerGap())
      );
      loginCardLayout.setVerticalGroup(
         loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(loginCardLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(logoLogin)
            .addGap(35, 35, 35)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(212, 212, 212)
            .addComponent(registerButton)
            .addContainerGap())
      );

      mainPanel.add(loginCard, "loginCard");

      otherLoginPanel.setBackground(new java.awt.Color(204, 204, 255));

      logoOther.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      homeOtherButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      homeOtherButton.setText("Home");
      homeOtherButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            homeOtherButtonActionPerformed(evt);
         }
      });

      registerOtherPanel.setBackground(new java.awt.Color(204, 204, 255));

      registerOtherLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      registerOtherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      registerOtherLabel.setText("Register");

      usernameOtherLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      usernameOtherLabel.setLabelFor(usernameBoxR);
      usernameOtherLabel.setText("Username");

      passwordOtherLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      passwordOtherLabel.setLabelFor(passwordBoxR1);
      passwordOtherLabel.setText("Password");

      emailOtherLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      emailOtherLabel.setLabelFor(emailBox);
      emailOtherLabel.setText("Email");

      emailPasswordOtherLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      emailPasswordOtherLabel.setLabelFor(passwordBoxR2);
      emailPasswordOtherLabel.setText("Email Password");

      emailServerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      emailServerLabel.setLabelFor(emailBox);
      emailServerLabel.setText("Email Server");

      submitOtherButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      submitOtherButton.setText("Submit");
      submitOtherButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitOtherButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout registerOtherPanelLayout = new javax.swing.GroupLayout(registerOtherPanel);
      registerOtherPanel.setLayout(registerOtherPanelLayout);
      registerOtherPanelLayout.setHorizontalGroup(
         registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerOtherPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(usernameOtherLabel)
               .addComponent(passwordOtherLabel)
               .addComponent(emailPasswordOtherLabel)
               .addComponent(emailOtherLabel)
               .addComponent(emailServerLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(emailServerBox)
               .addComponent(emailOtherBox)
               .addComponent(registerOtherLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
               .addComponent(usernameOtherBox, javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(passwordOtherBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
               .addComponent(emailPasswordOtherBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
            .addContainerGap(39, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerOtherPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(submitOtherButton)
            .addGap(96, 96, 96))
      );
      registerOtherPanelLayout.setVerticalGroup(
         registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerOtherPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(registerOtherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(usernameOtherLabel)
               .addComponent(usernameOtherBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordOtherBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(passwordOtherLabel))
            .addGap(18, 18, 18)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(emailOtherLabel)
               .addComponent(emailOtherBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(emailPasswordOtherBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(emailPasswordOtherLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(registerOtherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(emailServerLabel)
               .addComponent(emailServerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(submitOtherButton)
            .addContainerGap(61, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout otherLoginPanelLayout = new javax.swing.GroupLayout(otherLoginPanel);
      otherLoginPanel.setLayout(otherLoginPanelLayout);
      otherLoginPanelLayout.setHorizontalGroup(
         otherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(otherLoginPanelLayout.createSequentialGroup()
            .addGroup(otherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherLoginPanelLayout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(logoOther))
               .addGroup(otherLoginPanelLayout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(homeOtherButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 625, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(otherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherLoginPanelLayout.createSequentialGroup()
               .addGap(170, 170, 170)
               .addComponent(registerOtherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(186, Short.MAX_VALUE)))
      );
      otherLoginPanelLayout.setVerticalGroup(
         otherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(otherLoginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(logoOther)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
            .addComponent(homeOtherButton)
            .addContainerGap())
         .addGroup(otherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherLoginPanelLayout.createSequentialGroup()
               .addGap(95, 95, 95)
               .addComponent(registerOtherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(81, Short.MAX_VALUE)))
      );

      mainPanel.add(otherLoginPanel, "registerOtherCard");

      registerCard.setBackground(new java.awt.Color(204, 204, 255));

      logoRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      homeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      homeButton.setText("Home");
      homeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            homeButtonActionPerformed(evt);
         }
      });

      registerPanel.setBackground(new java.awt.Color(204, 204, 255));

      registerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      registerLabel.setText("Register");

      usernameLabelR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      usernameLabelR.setLabelFor(usernameBoxR);
      usernameLabelR.setText("Username");

      passwordLabelR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      passwordLabelR.setLabelFor(passwordBoxR1);
      passwordLabelR.setText("Password");

      passwordComfLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      passwordComfLabel.setLabelFor(passwordBoxR2);
      passwordComfLabel.setText("Confirm Password");

      emailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      emailLabel.setLabelFor(emailBox);
      emailLabel.setText("Email");

      submitButtonR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      submitButtonR.setText("Submit");
      submitButtonR.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitButtonRActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
      registerPanel.setLayout(registerPanelLayout);
      registerPanelLayout.setHorizontalGroup(
         registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(usernameLabelR)
               .addComponent(passwordLabelR)
               .addComponent(passwordComfLabel)
               .addComponent(emailLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
               .addComponent(usernameBoxR)
               .addComponent(passwordBoxR1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
               .addComponent(passwordBoxR2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
               .addComponent(emailBox))
            .addContainerGap(39, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(submitButtonR)
            .addGap(97, 97, 97))
      );
      registerPanelLayout.setVerticalGroup(
         registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(usernameLabelR)
               .addComponent(usernameBoxR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordBoxR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(passwordLabelR))
            .addGap(18, 18, 18)
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordComfLabel)
               .addComponent(passwordBoxR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(emailLabel)
               .addComponent(emailBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(submitButtonR)
            .addContainerGap(77, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout registerCardLayout = new javax.swing.GroupLayout(registerCard);
      registerCard.setLayout(registerCardLayout);
      registerCardLayout.setHorizontalGroup(
         registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerCardLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerCardLayout.createSequentialGroup()
                  .addComponent(homeButton)
                  .addGap(0, 615, Short.MAX_VALUE))
               .addGroup(registerCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(logoRegister)))
            .addContainerGap())
         .addGroup(registerCardLayout.createSequentialGroup()
            .addGap(171, 171, 171)
            .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      registerCardLayout.setVerticalGroup(
         registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(registerCardLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(logoRegister)
            .addGap(35, 35, 35)
            .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
            .addComponent(homeButton)
            .addContainerGap())
      );

      mainPanel.add(registerCard, "registerCard");

      inboxCard.setBackground(new java.awt.Color(204, 204, 255));

      logoInbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      logoutButton.setText("Log Out");
      logoutButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutButtonActionPerformed(evt);
         }
      });

      inboxLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      inboxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      inboxLabel.setText("Inbox");

      inboxPanel.setBackground(new java.awt.Color(204, 204, 255));

      composeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      composeButton.setText("Compose");
      composeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            composeButtonActionPerformed(evt);
         }
      });

      deleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      deleteButton.setText("Delete");

      openButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      openButton.setText("Open");
      openButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            openButtonActionPerformed(evt);
         }
      });

      inboxTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null}
         },
         new String [] {
            "Sender", "Title", "Content"
         }
      ) {
         boolean[] canEdit = new boolean [] {
            false, false, false
         };

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      jScrollPane2.setViewportView(inboxTable);

      javax.swing.GroupLayout inboxPanelLayout = new javax.swing.GroupLayout(inboxPanel);
      inboxPanel.setLayout(inboxPanelLayout);
      inboxPanelLayout.setHorizontalGroup(
         inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inboxPanelLayout.createSequentialGroup()
            .addContainerGap(66, Short.MAX_VALUE)
            .addGroup(inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addGroup(inboxPanelLayout.createSequentialGroup()
                  .addComponent(openButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(deleteButton))
               .addGroup(inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(composeButton)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(67, 67, 67))
      );
      inboxPanelLayout.setVerticalGroup(
         inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inboxPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(composeButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(inboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(deleteButton)
               .addComponent(openButton))
            .addGap(26, 26, 26))
      );

      javax.swing.GroupLayout inboxCardLayout = new javax.swing.GroupLayout(inboxCard);
      inboxCard.setLayout(inboxCardLayout);
      inboxCardLayout.setHorizontalGroup(
         inboxCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(inboxCardLayout.createSequentialGroup()
            .addGroup(inboxCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inboxCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(logoutButton))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inboxCardLayout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(inboxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(logoInbox)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inboxCardLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(inboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      inboxCardLayout.setVerticalGroup(
         inboxCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(inboxCardLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(inboxCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(logoInbox)
               .addComponent(inboxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22)
            .addComponent(inboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton)
            .addContainerGap())
      );

      mainPanel.add(inboxCard, "inboxCard");

      composeCard.setBackground(new java.awt.Color(204, 204, 255));

      composeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      inboxButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      inboxButton.setText("Inbox");
      inboxButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            inboxButtonActionPerformed(evt);
         }
      });

      composePanel.setBackground(new java.awt.Color(204, 204, 255));

      composeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      composeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      composeLabel.setText("Compose");

      toLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      toLabel.setLabelFor(toBox);
      toLabel.setText("To:");

      subjectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      subjectLabel.setLabelFor(subjectBox);
      subjectLabel.setText("Subject:");

      messageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      messageLabel.setLabelFor(toBox);
      messageLabel.setText("Message:");

      sendButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      sendButton.setText("Send");
      sendButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sendButtonActionPerformed(evt);
         }
      });

      messageArea.setColumns(20);
      messageArea.setRows(5);
      jScrollPane1.setViewportView(messageArea);

      javax.swing.GroupLayout composePanelLayout = new javax.swing.GroupLayout(composePanel);
      composePanel.setLayout(composePanelLayout);
      composePanelLayout.setHorizontalGroup(
         composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(composePanelLayout.createSequentialGroup()
            .addContainerGap(69, Short.MAX_VALUE)
            .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(sendButton, javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, composePanelLayout.createSequentialGroup()
                  .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(messageLabel)
                     .addComponent(toLabel)
                     .addComponent(subjectLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(composeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(toBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subjectBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))))
            .addContainerGap(65, Short.MAX_VALUE))
      );
      composePanelLayout.setVerticalGroup(
         composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(composePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(composeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(toLabel)
               .addComponent(toBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(subjectLabel)
               .addComponent(subjectBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(composePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(messageLabel)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sendButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout composeCardLayout = new javax.swing.GroupLayout(composeCard);
      composeCard.setLayout(composeCardLayout);
      composeCardLayout.setHorizontalGroup(
         composeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(composeCardLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(composeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, composeCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(composeLogo))
               .addGroup(composeCardLayout.createSequentialGroup()
                  .addComponent(inboxButton)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(composeCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(composePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      composeCardLayout.setVerticalGroup(
         composeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(composeCardLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(composeLogo)
            .addGap(35, 35, 35)
            .addComponent(composePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
            .addComponent(inboxButton)
            .addContainerGap())
      );

      mainPanel.add(composeCard, "composeCard");

      openCard.setBackground(new java.awt.Color(204, 204, 255));

      openLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BmailLogoSmall.png"))); // NOI18N

      inboxButtonO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      inboxButtonO.setText("Inbox");
      inboxButtonO.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            inboxButtonOActionPerformed(evt);
         }
      });

      openPanel.setBackground(new java.awt.Color(204, 204, 255));

      fromLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      fromLabel.setLabelFor(fromBox);
      fromLabel.setText("From:");

      subjectLabelO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      subjectLabelO.setLabelFor(subjectBoxO);
      subjectLabelO.setText("Subject:");

      messageLabelO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      messageLabelO.setLabelFor(toBox);
      messageLabelO.setText("Message:");

      deleteButtonO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      deleteButtonO.setText("Delete");
      deleteButtonO.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            deleteButtonOActionPerformed(evt);
         }
      });

      messageAreaO.setColumns(20);
      messageAreaO.setRows(5);
      jScrollPane3.setViewportView(messageAreaO);

      javax.swing.GroupLayout openPanelLayout = new javax.swing.GroupLayout(openPanel);
      openPanel.setLayout(openPanelLayout);
      openPanelLayout.setHorizontalGroup(
         openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(openPanelLayout.createSequentialGroup()
            .addContainerGap(69, Short.MAX_VALUE)
            .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(deleteButtonO)
               .addGroup(openPanelLayout.createSequentialGroup()
                  .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(messageLabelO)
                     .addComponent(fromLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(subjectLabelO, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(jScrollPane3)
                     .addComponent(fromBox, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(subjectBoxO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))))
            .addContainerGap(76, Short.MAX_VALUE))
      );
      openPanelLayout.setVerticalGroup(
         openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(openPanelLayout.createSequentialGroup()
            .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(fromBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(fromLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(subjectLabelO)
               .addComponent(subjectBoxO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(messageLabelO)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(deleteButtonO)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout openCardLayout = new javax.swing.GroupLayout(openCard);
      openCard.setLayout(openCardLayout);
      openCardLayout.setHorizontalGroup(
         openCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(openCardLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(openCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(openLogo))
               .addGroup(openCardLayout.createSequentialGroup()
                  .addComponent(inboxButtonO)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(openCardLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(openPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      openCardLayout.setVerticalGroup(
         openCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(openCardLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(openLogo)
            .addGap(44, 44, 44)
            .addComponent(openPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addComponent(inboxButtonO)
            .addContainerGap())
      );

      mainPanel.add(openCard, "openCard");

      getContentPane().add(mainPanel, "card4");

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       // check username and password against database
		//if valid move to inbox
		//if invalid 
		JOptionPane.showMessageDialog(null, "Invalid username or password");
		CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inboxCard");
   }//GEN-LAST:event_submitButtonActionPerformed

   private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "registerCard");
   }//GEN-LAST:event_registerButtonActionPerformed

   private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "loginCard");
   }//GEN-LAST:event_homeButtonActionPerformed

   private void submitButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonRActionPerformed
      // check if user is in database yet
		JOptionPane.showMessageDialog(null, "Username is taken.");
		usernameBoxR.setText("");
		passwordBoxR1.setText("");
		passwordBoxR2.setText("");
		emailBox.setText("");
		//if not add them and go to inbox
   }//GEN-LAST:event_submitButtonRActionPerformed

   private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "loginCard");
   }//GEN-LAST:event_logoutButtonActionPerformed

   private void composeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "composeCard");
   }//GEN-LAST:event_composeButtonActionPerformed

   private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "openCard");
   }//GEN-LAST:event_openButtonActionPerformed

   private void inboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inboxCard");
   }//GEN-LAST:event_inboxButtonActionPerformed

   private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
      //send email or
		JOptionPane.showMessageDialog(null, "Email address is invalid");
   }//GEN-LAST:event_sendButtonActionPerformed

   private void inboxButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonOActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inboxCard");
   }//GEN-LAST:event_inboxButtonOActionPerformed

   private void deleteButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonOActionPerformed
      // delete email opened
   }//GEN-LAST:event_deleteButtonOActionPerformed

   private void homeOtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeOtherButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "loginCard");
   }//GEN-LAST:event_homeOtherButtonActionPerformed

   private void otherEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherEmailButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "registerOtherCard");
   }//GEN-LAST:event_otherEmailButtonActionPerformed

   private void submitOtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitOtherButtonActionPerformed
      CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inboxCard");
   }//GEN-LAST:event_submitOtherButtonActionPerformed

	
	public static void main(String args[]) {
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bmail().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton composeButton;
   private javax.swing.JPanel composeCard;
   private javax.swing.JLabel composeLabel;
   private javax.swing.JLabel composeLogo;
   private javax.swing.JPanel composePanel;
   private javax.swing.JButton deleteButton;
   private javax.swing.JButton deleteButtonO;
   private javax.swing.JTextField emailBox;
   private javax.swing.JLabel emailLabel;
   private javax.swing.JTextField emailOtherBox;
   private javax.swing.JLabel emailOtherLabel;
   private javax.swing.JPasswordField emailPasswordOtherBox;
   private javax.swing.JLabel emailPasswordOtherLabel;
   private javax.swing.JTextField emailServerBox;
   private javax.swing.JLabel emailServerLabel;
   private javax.swing.JTextField fromBox;
   private javax.swing.JLabel fromLabel;
   private javax.swing.JButton homeButton;
   private javax.swing.JButton homeOtherButton;
   private javax.swing.JButton inboxButton;
   private javax.swing.JButton inboxButtonO;
   private javax.swing.JPanel inboxCard;
   private javax.swing.JLabel inboxLabel;
   private javax.swing.JPanel inboxPanel;
   private javax.swing.JTable inboxTable;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JPanel loginCard;
   private javax.swing.JLabel loginLabel;
   private javax.swing.JPanel loginPanel;
   private javax.swing.JLabel logoInbox;
   private javax.swing.JLabel logoLogin;
   private javax.swing.JLabel logoOther;
   private javax.swing.JLabel logoRegister;
   private javax.swing.JButton logoutButton;
   private javax.swing.JPanel mainPanel;
   private javax.swing.JTextArea messageArea;
   private javax.swing.JTextArea messageAreaO;
   private javax.swing.JLabel messageLabel;
   private javax.swing.JLabel messageLabelO;
   private javax.swing.JButton openButton;
   private javax.swing.JPanel openCard;
   private javax.swing.JLabel openLogo;
   private javax.swing.JPanel openPanel;
   private javax.swing.JButton otherEmailButton;
   private javax.swing.JPanel otherLoginPanel;
   private javax.swing.JPasswordField passwordBox;
   private javax.swing.JPasswordField passwordBoxR1;
   private javax.swing.JPasswordField passwordBoxR2;
   private javax.swing.JLabel passwordComfLabel;
   private javax.swing.JLabel passwordLabel;
   private javax.swing.JLabel passwordLabelR;
   private javax.swing.JPasswordField passwordOtherBox;
   private javax.swing.JLabel passwordOtherLabel;
   private javax.swing.JButton registerButton;
   private javax.swing.JPanel registerCard;
   private javax.swing.JLabel registerLabel;
   private javax.swing.JLabel registerOtherLabel;
   private javax.swing.JPanel registerOtherPanel;
   private javax.swing.JPanel registerPanel;
   private javax.swing.JButton sendButton;
   private javax.swing.JTextField subjectBox;
   private javax.swing.JTextField subjectBoxO;
   private javax.swing.JLabel subjectLabel;
   private javax.swing.JLabel subjectLabelO;
   private javax.swing.JButton submitButton;
   private javax.swing.JButton submitButtonR;
   private javax.swing.JButton submitOtherButton;
   private javax.swing.JTextField toBox;
   private javax.swing.JLabel toLabel;
   private javax.swing.JTextField usernameBox;
   private javax.swing.JTextField usernameBoxR;
   private javax.swing.JLabel usernameLabel;
   private javax.swing.JLabel usernameLabelR;
   private javax.swing.JTextField usernameOtherBox;
   private javax.swing.JLabel usernameOtherLabel;
   // End of variables declaration//GEN-END:variables
}
